version: '3.2'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: RootPass1992
      MYSQL_DATABASE: blansplatform
    networks:
      - application

  rest:
    container_name: rest
    build:
      context: ./rest
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - application
    depends_on:
      - mysql-db
    restart: on-failure


#  ui:
#    container_name: userInterface
#    build:
#      context: ./ui
#      dockerfile: Dockerfile
#    volumes:
#      - ./app
#      - /app/node_modules
#    ports:
#      - 8000:80
#    networks:
#      - application


networks:
  application:
    driver: bridge
